//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Turtle.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Turtle.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;EXAMPLES&gt;
        ///  &lt;Plante&gt;
        ///    &lt;symbols&gt;X&lt;/symbols&gt;
        ///    &lt;symbols&gt;F&lt;/symbols&gt;
        ///    &lt;symbols&gt;+&lt;/symbols&gt;
        ///    &lt;symbols&gt;-&lt;/symbols&gt;
        ///    &lt;symbols&gt;[&lt;/symbols&gt;
        ///    &lt;symbols&gt;]&lt;/symbols&gt;
        ///    &lt;seed&gt;X&lt;/seed&gt;
        ///    &lt;rules&gt;
        ///      &lt;X&gt;F+[[X]-X]-F[-FX]+X&lt;/X&gt;
        ///      &lt;F&gt;FF&lt;/F&gt;
        ///    &lt;/rules&gt;
        ///    &lt;angle&gt;25&lt;/angle&gt;
        ///  &lt;/Plante&gt;
        ///  &lt;Koch&gt;
        ///    &lt;symbols&gt;F&lt;/symbols&gt;
        ///    &lt;seed&gt;F&lt;/seed&gt;
        ///    &lt;rules&gt;
        ///      &lt;F&gt;F+F−F−F+F&lt;/F&gt;
        ///    &lt;/rules&gt;
        ///    &lt;angle&gt;90&lt;/angle&gt;
        ///  &lt;/Koch&gt;
        ///  &lt;Dragon&gt;
        ///    &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExamplesData {
            get {
                return ResourceManager.GetString("ExamplesData", resourceCulture);
            }
        }
    }
}
